# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [3]:
url='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv'
babyname= pd.read_csv(url, sep=',')

### Step 4. See the first 10 entries

In [5]:
babyname.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [7]:
del babyname['Unnamed: 0']


del babyname['Id']

babyname.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. What year has the highest number of baby names in the dataset?

In [8]:
babyname['Name'].value_counts()

Name
Riley      1112
Avery      1080
Jordan     1073
Peyton     1064
Hayden     1049
           ...
Kong          1
Adrion        1
Braun         1
Evrett        1
Coalton       1
Name: count, Length: 17632, dtype: int64

In [17]:
babyname.groupby("Year").count()

       Name  Gender  State  Count
Year
2004  86420   86420  86420  86420
2005  88494   88494  88494  88494
2006  91803   91803  91803  91803
2007  94332   94332  94332  94332
2008  94970   94970  94970  94970
2009  94609   94609  94609  94609
2010  93307   93307  93307  93307
2011  92545   92545  92545  92545
2012  93024   93024  93024  93024
2013  92743   92743  92743  92743
2014  94148   94148  94148  94148

In [16]:
babyname.groupby("Year")["Name"].count().sort_values(ascending=False)[:1]

Year
2008    94970
Name: Name, dtype: int64

### Step 7. Is there more male or female names in the dataset?

In [9]:
babyname['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [22]:
names = babyname.groupby("Name")['Count'].sum()
names[:10]

Name
Aaban        12
Aadan        23
Aadarsh       5
Aaden      3426
Aadhav        6
Aadhya      453
Aadi        307
Aadin         5
Aadit        18
Aaditya      97
Name: Count, dtype: int64

### Step 9. How many different names exist in the dataset?

In [23]:
names.count()

np.int64(17632)

### Step 10. What is the name with most occurrences?

In [25]:
names.sort_values(ascending=False)

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
             ...
Jihaad           5
Cadynce          5
Caelen           5
Mileigh          5
Milos            5
Name: Count, Length: 17632, dtype: int64

### Step 11. How many different names have the least occurrences?

In [35]:
len(names[names == names.min()])

2578

In [33]:
names[names == names.min()]

Name
Aadarsh     5
Aadin       5
Aaima       5
Aalaya      5
Aaminah     5
           ..
Zyien       5
Zyire       5
Zykeriah    5
Zykierra    5
Zymari      5
Name: Count, Length: 2578, dtype: int64

In [34]:
names[names == names.min()].count()

np.int64(2578)

### Step 12. What is the median name occurrence?

In [36]:
names[names == names.median()]

Name
Aishani    49
Alara      49
Alysse     49
Ameir      49
Anely      49
           ..
Sriram     49
Trinton    49
Vita       49
Yoni       49
Zuleima    49
Name: Count, Length: 66, dtype: int64

### Step 13. What is the standard deviation of names?

In [37]:
names.std()

np.float64(11006.06946789057)

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [38]:
names.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64