# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [3]:
url='https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo= pd.read_csv(url, sep='\t')

In [6]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

In [7]:
chipo[:8]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75

### Step 4. How many products cost more than $10.00?

In [11]:
# 假設附餐會影響到價格
chipo[chipo['item_name'] == 'Chicken Bowl'][['item_name', 'choice_description', 'item_price', 'quantity']].head(10)

,item_name,choice_description,item_price,quantity
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,2
5,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,1
13,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,1
19,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75,1
26,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49,1
42,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25,1
76,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$8.75,1
78,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,1
99,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75,1
110,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75,1

In [17]:
# 去除quantity的影響
chipo['price']=chipo['item_price'].str.replace('$', '').astype(float)
chipo['unit_price'] = chipo['price'] / chipo['quantity'].astype(float)
chipo['unit_price']

0        2.39
1        3.39
2        3.39
3        2.39
4        8.49
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: unit_price, Length: 4622, dtype: float64

In [21]:
# 建立multiIndex，做兩次groupby
product= chipo.groupby(['item_name', 'choice_description'])['unit_price']
product.size()

item_name          choice_description
6 Pack Soft Drink  [Coke]                                                                                                               21
                   [Diet Coke]                                                                                                          24
                   [Lemonade]                                                                                                            2
                   [Nestea]                                                                                                              2
                   [Sprite]                                                                                                              5
                                                                                                                                        ..
Veggie Soft Tacos  [Fresh Tomato Salsa, [Black Beans, Cheese, Sour Cream, Lettuce]]                                                      1
                   [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]     1
                   [Roasted Chili Corn Salsa (Medium), [Black Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                       1
                   [Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Pinto Beans, Cheese, Lettuce]]                            1
                   [Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]                       1
Name: unit_price, Length: 1859, dtype: int64

In [22]:
# 就算把choice_description字串爆開，大概也算不出各配菜單價:(
# 「product」在這題的定義就是 item_name + choice_description 的唯一組合!不是光看 item_name。

In [29]:
series_product=product.first()

In [32]:
series_product.between(0,10)

item_name          choice_description
6 Pack Soft Drink  [Coke]                                                                                                                True
                   [Diet Coke]                                                                                                           True
                   [Lemonade]                                                                                                            True
                   [Nestea]                                                                                                              True
                   [Sprite]                                                                                                              True
                                                                                                                                        ...
Veggie Soft Tacos  [Fresh Tomato Salsa, [Black Beans, Cheese, Sour Cream, Lettuce]]                                                      True
                   [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]    False
                   [Roasted Chili Corn Salsa (Medium), [Black Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                       True
                   [Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Pinto Beans, Cheese, Lettuce]]                            True
                   [Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]                      False
Name: unit_price, Length: 1859, dtype: bool

In [33]:
series_product > 10

item_name          choice_description
6 Pack Soft Drink  [Coke]                                                                                                               False
                   [Diet Coke]                                                                                                          False
                   [Lemonade]                                                                                                           False
                   [Nestea]                                                                                                             False
                   [Sprite]                                                                                                             False
                                                                                                                                        ...
Veggie Soft Tacos  [Fresh Tomato Salsa, [Black Beans, Cheese, Sour Cream, Lettuce]]                                                     False
                   [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]     True
                   [Roasted Chili Corn Salsa (Medium), [Black Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                      False
                   [Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Pinto Beans, Cheese, Lettuce]]                           False
                   [Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]                       True
Name: unit_price, Length: 1859, dtype: bool

In [34]:
(series_product > 10).sum()

np.int64(707)

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [36]:
series_product

item_name          choice_description
6 Pack Soft Drink  [Coke]                                                                                                                6.49
                   [Diet Coke]                                                                                                           6.49
                   [Lemonade]                                                                                                            6.49
                   [Nestea]                                                                                                              6.49
                   [Sprite]                                                                                                              6.49
                                                                                                                                        ...
Veggie Soft Tacos  [Fresh Tomato Salsa, [Black Beans, Cheese, Sour Cream, Lettuce]]                                                      8.75
                   [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Black Beans, Pinto Beans, Cheese, Sour Cream, Guacamole, Lettuce]]    11.25
                   [Roasted Chili Corn Salsa (Medium), [Black Beans, Fajita Veggies, Cheese, Sour Cream, Lettuce]]                       8.49
                   [Roasted Chili Corn Salsa, [Fajita Vegetables, Black Beans, Pinto Beans, Cheese, Lettuce]]                            8.75
                   [Tomatillo Red Chili Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Guacamole, Lettuce]]                      11.25
Name: unit_price, Length: 1859, dtype: float64

### Step 6. Sort by the name of the item

In [37]:
chipo.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price,price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98,12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49,6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49,6.49,6.49
...,...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49,8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49,8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [49]:
most_expensive_item=chipo.sort_values(['unit_price'],ascending= False)[:1]
most_expensive_item

,order_id,quantity,item_name,choice_description,item_price,price,unit_price
3749,1499,1,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89,11.89

In [50]:
chipo.sort_values(['unit_price'], ascending=False)[:1]['quantity']

3749    1
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [51]:
chipo[chipo["item_name"]=="Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [52]:
chipo[ ( chipo["item_name"]=="Canned Soda" ) & ( chipo["quantity"]>1 )].shape[0]

20